### ISSUE TITLE
Serialization issue when adding media Ids

### ISSUE THREAD

**Issue by alvarolorentedev** [typescriptlibs/tsl-mastodon-api#32]
**Describe the bug**
when you create a status if media ids are pased the array is serialized as a string, causing it to fail silently, and only generates a text post.

**To Reproduce**
1. call:
```js
client.postStatus({
            status: post.content,
            media_ids: [attachment.json.id]

        })
```
2. See post with only text

**Expected behavior**
Se the post with an immage

**Package (please complete the following information):**
 - Source: [e.g. NPM, GitHub]
 - Version: [e.g. 1.0.0, main]

**Additional context**
I intercepted the call:
```json
https://mastodon.social/api/v1/statuses {
  "follow": 9,
  "redirect": "follow",
  "headers": {
    "accept": "*/*",
    "authorization": "Bearer -----"
  },
  "method": "POST",
  "signal": {},
  "body": {
    "status": "test post",
    "media_ids": "[\"111891947490630091\"]"
  }
}
```

the expected serialization would be

```json
https://mastodon.social/api/v1/statuses {
  "follow": 9,
  "redirect": "follow",
  "headers": {
    "accept": "*/*",
    "authorization": "Bearer -----"
  },
  "method": "POST",
  "signal": {},
  "body": {
    "status": "test post",
    "media_ids": ["111891947490630091"]
  }
}
```

**Comment by sophiebremer** [comment]
Hello @alvarolorentedev,
Thank you reporting it. I am able to reproduce the issue and prepare a solution.

Internal note: URLSearchParams requires [bracket notation](https://docs.joinmastodon.org/client/intro/#array) for arrays and records.

**Comment by sophiebremer** [comment]
Hello again! A bugfix has been created. Please let me know, if this works for you.

**Comment by alvarolorentedev** [comment]
awesome, I will give it a try later today. Thanks for the fast response.

**Comment by sophiebremer** [comment]
@alvarolorentedev
Some additional issues with multiple files in form data have been fixed in the PR.
A CLI with a reference implementation has also been added.
